### PR TITLE
Fix for 1.16.2

### PR DESCRIPTION
**Pull request by R3alCl0ud**
Changed how the biome registry is grabbed so that it works on 1.16.2

### CODE REVIEW

**Comment by R3alCl0ud** [comment]
I also bumped the version to 0.1.3

**Comment by khang06** [comment]
still needs to intercept ResourcePackManager.createResourcePacks instead of ReloadableResourceManagerImpl.beginMonitoredReload, otherwise it tries to add the ctm resource pack to an immutable list and crash on boot

```Java
@Mixin(ResourcePackManager.class)
public class ResourcePackManagerMixin {
	@Shadow
	private List<ResourcePackProfile> enabled;
	
	@Overwrite
	public List<ResourcePack> createResourcePacks() {
		ArrayList<ResourcePack> packs = new ArrayList<ResourcePack>(this.enabled.stream().map(ResourcePackProfile::createResourcePack).collect(Collectors.toList()));
		
		ConnectedBlockTextures.RESOURCE_PACK_PRIORITY_MAP.clear();
		for(int i = 0; i < packs.size(); i++) {
			ConnectedBlockTextures.RESOURCE_PACK_PRIORITY_MAP.put(packs.get(i).getName(), i);
		}
		packs.add(ConnectedBlockTextures.resourcePack = new CBTResourcePack(MinecraftClient.getInstance().getResourceManager()));
		
		return packs;
	}
}
```

(this code overwrites it because i can't just modify the return value, but i'm sure you can find a better way)

**Comment by R3alCl0ud** [comment]
I've been using my patch for the last few weeks and have never gotten a crash that was the result of cbt

**Comment by R3alCl0ud** [comment]
Can you give better steps to reproduce @khang06 I can't recreate the issue you are having.
I've been able to run cbt on 1.16.2 without any problems since I made it work 11 days ago.

**Comment by khang06** [comment]
looks like that issue was actually caused by me manually merging the diff into my own branch which had an updated fabric api, so it isn't actually a problem with this pull request. sorry about that.

for the record, you can reproduce it by setting fabric_version to 0.20.1+build.401-1.16 (that's what i get for not reading issues lol)

**Pull request closed without merging**
